### ISSUE TITLE
single character passwords considered (very)/strong

### ISSUE THREAD

**Issue by RauchenwaldC** [DimitarChristoff/StrongPass#4]
Thanks for developing this amazing class.

I noted that passwords like "aaaaaaaaaaaaaaaaaaaaaaaaa" are considered "very strong" as well.

Maybe consider using the number of different characters used instead of length at line 297

`// bonus for length per char
score && (score += len);
return score;`

**Comment by DimitarChristoff** [comment]
brute force guessing of a pass that is 25 characters? for 13 characters it would take 64 years...
